version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-clusters.xml:/etc/clickhouse-server/config.d/clusters.xml
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: posthog
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: posthog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    image: posthog/posthog:latest
    depends_on:
      - clickhouse
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://posthog:posthog@postgres:5432/posthog
      REDIS_URL: redis://redis:6379
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_CLUSTER: posthog
      CLICKHOUSE_MIGRATIONS_CLUSTER: posthog_migrations
      SECRET_KEY: your_secret_key_here
    ports:
      - "8000:8000"

  worker:
    image: posthog/posthog:latest
    command: worker
    depends_on:
      - web
    environment:
      DATABASE_URL: postgres://posthog:posthog@postgres:5432/posthog
      REDIS_URL: redis://redis:6379
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_CLUSTER: posthog
      CLICKHOUSE_MIGRATIONS_CLUSTER: posthog_migrations
      SECRET_KEY: your_secret_key_here

  plugin-server:
    image: posthog/posthog:latest
    command: plugin-server
    depends_on:
      - web
    environment:
      DATABASE_URL: postgres://posthog:posthog@postgres:5432/posthog
      REDIS_URL: redis://redis:6379
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_CLUSTER: posthog
      CLICKHOUSE_MIGRATIONS_CLUSTER: posthog_migrations
      SECRET_KEY: your_secret_key_here

volumes:
  clickhouse-data:
  postgres-data:
