version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: posthog
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: posthog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posthog"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  redis:
    image: redis:7.2.1-alpine
    restart: unless-stopped
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse:
    image: clickhouse/clickhouse-server:25.3.6.56
    restart: unless-stopped
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: posthog
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    image: posthog/posthog:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    expose:
      - "8000" 
    environment:
      SITE_URL: https://dashboard.reccan.nl
      SECRET_KEY: 62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0
      DATABASE_URL: postgres://posthog:posthog@postgres:5432/posthog
      REDIS_URL: redis://redis:6379/
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_SECURE: "false"
      CLICKHOUSE_VERIFY: "false"
      DISABLE_SECURE_SSL_REDIRECT: "true"
      SECURE_PROXY_SSL_HEADER: HTTP_X_FORWARDED_PROTO,https
      IS_BEHIND_PROXY: "true"
    command: bash -c "sleep 10 && ./bin/migrate && ./bin/docker-server"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/_health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    image: posthog/posthog:latest
    restart: unless-stopped
    depends_on:
      - web
    environment:
      DATABASE_URL: postgres://posthog:posthog@postgres:5432/posthog
      REDIS_URL: redis://redis:6379/
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_SECURE: "false"
      CLICKHOUSE_VERIFY: "false"
      SECRET_KEY: 62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0
    command: bash -c "sleep 30 && ./bin/docker-worker-celery --with-scheduler"

volumes:
  postgres-data:
  clickhouse-data:
