version: '3.8'
services:
  db:
    image: 'postgres:17.5-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_USER: posthog
      POSTGRES_DB: posthog
      POSTGRES_PASSWORD: posthog
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posthog"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: 'redis:7.2.1-alpine'
    restart: unless-stopped
    command: 'redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  zookeeper:
    image: 'zookeeper:3.8.2'
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'bitnami/kafka:4.0.0'
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'true'

  clickhouse:
    image: 'clickhouse/clickhouse-server:25.3.6.56'
    restart: unless-stopped
    depends_on:
      - kafka
      - zookeeper
    volumes:
        - ./posthog/posthog/idl:/idl
        #- ./posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        #- ./posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
        #- ./posthog/docker/clickhouse/config.d/default.xml:/etc/clickhouse-server/config.d/default.xml
        #- ./posthog/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
        #- ./posthog/docker/clickhouse/user_defined_function.xml:/etc/clickhouse-server/user_defined_function.xml
        #- ./posthog/posthog/user_scripts:/var/lib/clickhouse/user_scripts
        #- clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: posthog
      CLICKHOUSE_USER: posthog
      CLICKHOUSE_PASSWORD: posthog
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  object_storage:
    image: 'minio/minio:RELEASE.2025-02-18T16-25-55Z'
    restart: unless-stopped
    volumes:
      - 'object_storage:/data'
    environment:
      MINIO_ROOT_USER: object_storage_root_user
      MINIO_ROOT_PASSWORD: object_storage_root_password
    command: 'server --address ":19000" --console-address ":19001" /data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    image: 'posthog/posthog:012e85e72ccc120dbf17e20ef5f108972c22a495'
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - clickhouse
      - kafka
      - object_storage
    expose:
      - '8000'
    environment:
      SERVICE_FQDN_WEB: 'https://dashboard.reccan.nl'
      SITE_URL: 'https://dashboard.reccan.nl'
      SECRET_KEY: '62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0'
      ENCRYPTION_KEY: '62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0'
      DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
      REDIS_URL: 'redis://redis:6379/'
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_USER: posthog
      CLICKHOUSE_PASSWORD: posthog
      CLICKHOUSE_SECURE: 'false'
      CLICKHOUSE_VERIFY: 'false'
      CLICKHOUSE_CLUSTER: 'posthog'
      CLICKHOUSE_REPLICATION: 'false'
      CLICKHOUSE_DISABLE_EXTERNAL_SCHEMAS: 'true'
      CLICKHOUSE_MIGRATIONS_CLUSTER: 'posthog'
      KAFKA_HOSTS: 'kafka:9092'
      OBJECT_STORAGE_ENABLED: 'true'
      OBJECT_STORAGE_ENDPOINT: 'http://object_storage:19000'
      OBJECT_STORAGE_ACCESS_KEY_ID: object_storage_root_user
      OBJECT_STORAGE_SECRET_ACCESS_KEY: object_storage_root_password
      OBJECT_STORAGE_BUCKET: posthog
      SKIP_SERVICE_VERSION_REQUIREMENTS: '1'
      SKIP_ASYNC_MIGRATIONS_SETUP: '1'
      ASYNC_MIGRATIONS_DISABLE_AUTO_ROLLBACK: '1'
      IS_BEHIND_PROXY: 'true'
      TRUST_ALL_PROXIES: 'true'
      ALLOWED_HOSTS: '*'
      DISABLE_SECURE_SSL_REDIRECT: 'true'
      SECURE_PROXY_SSL_HEADER: 'HTTP_X_FORWARDED_PROTO,https'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.posthog.rule=Host(`dashboard.reccan.nl`)'
      - 'traefik.http.routers.posthog.entrypoints=https'
      - 'traefik.http.routers.posthog.tls.certresolver=letsencrypt'
      - 'traefik.http.services.posthog.loadbalancer.server.port=8000'
    command: 'bash -c "sleep 30 && ./bin/start-backend"'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    image: 'posthog/posthog:012e85e72ccc120dbf17e20ef5f108972c22a495'
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - clickhouse
      - kafka
      - object_storage
    environment:
      SERVICE_FQDN_WEB: 'https://dashboard.reccan.nl'
      SITE_URL: 'https://dashboard.reccan.nl'
      SECRET_KEY: '62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0'
      ENCRYPTION_KEY: '62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0'
      DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
      REDIS_URL: 'redis://redis:6379/'
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_USER: posthog
      CLICKHOUSE_PASSWORD: posthog
      CLICKHOUSE_SECURE: 'false'
      CLICKHOUSE_VERIFY: 'false'
      CLICKHOUSE_CLUSTER: 'posthog'
      CLICKHOUSE_REPLICATION: 'false'
      CLICKHOUSE_DISABLE_EXTERNAL_SCHEMAS: 'true'
      CLICKHOUSE_MIGRATIONS_CLUSTER: 'posthog'
      KAFKA_HOSTS: 'kafka:9092'
      OBJECT_STORAGE_ENABLED: 'true'
      OBJECT_STORAGE_ENDPOINT: 'http://object_storage:19000'
      OBJECT_STORAGE_ACCESS_KEY_ID: object_storage_root_user
      OBJECT_STORAGE_SECRET_ACCESS_KEY: object_storage_root_password
      OBJECT_STORAGE_BUCKET: posthog
      SKIP_SERVICE_VERSION_REQUIREMENTS: '1'
      SKIP_ASYNC_MIGRATIONS_SETUP: '1'
      ASYNC_MIGRATIONS_DISABLE_AUTO_ROLLBACK: '1'
      IS_BEHIND_PROXY: 'true'
      TRUST_ALL_PROXIES: 'true'
      ALLOWED_HOSTS: '*'
      DISABLE_SECURE_SSL_REDIRECT: 'true'
      SECURE_PROXY_SSL_HEADER: 'HTTP_X_FORWARDED_PROTO,https'
    command: 'bash -c "sleep 45 && ./bin/start-worker"'
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "-v", "grep", "|", "grep", "celery"]
      interval: 60s
      timeout: 30s
      retries: 3

  plugins:
    image: 'posthog/posthog:012e85e72ccc120dbf17e20ef5f108972c22a495'
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - clickhouse
      - kafka
      - object_storage
    environment:
      SERVICE_FQDN_WEB: 'https://dashboard.reccan.nl'
      SITE_URL: 'https://dashboard.reccan.nl'
      SECRET_KEY: '62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0'
      ENCRYPTION_KEY: '62b4b1a783411893874d7f7a0b1ce48180941ebeabc126911a48426256d67ea0'
      DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
      REDIS_URL: 'redis://redis:6379/'
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_USER: posthog
      CLICKHOUSE_PASSWORD: posthog
      CLICKHOUSE_SECURE: 'false'
      CLICKHOUSE_VERIFY: 'false'
      CLICKHOUSE_CLUSTER: 'posthog'
      CLICKHOUSE_REPLICATION: 'false'
      CLICKHOUSE_DISABLE_EXTERNAL_SCHEMAS: 'true'
      CLICKHOUSE_MIGRATIONS_CLUSTER: 'posthog'
      KAFKA_HOSTS: 'kafka:9092'
      OBJECT_STORAGE_ENABLED: 'true'
      OBJECT_STORAGE_ENDPOINT: 'http://object_storage:19000'
      OBJECT_STORAGE_ACCESS_KEY_ID: object_storage_root_user
      OBJECT_STORAGE_SECRET_ACCESS_KEY: object_storage_root_password
      OBJECT_STORAGE_BUCKET: posthog
      SKIP_SERVICE_VERSION_REQUIREMENTS: '1'
      SKIP_ASYNC_MIGRATIONS_SETUP: '1'
      ASYNC_MIGRATIONS_DISABLE_AUTO_ROLLBACK: '1'
      IS_BEHIND_PROXY: 'true'
      TRUST_ALL_PROXIES: 'true'
      ALLOWED_HOSTS: '*'
      DISABLE_SECURE_SSL_REDIRECT: 'true'
      SECURE_PROXY_SSL_HEADER: 'HTTP_X_FORWARDED_PROTO,https'
    command: 'bash -c "sleep 90 && ./bin/plugin-server"'
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "-v", "grep", "|", "grep", "plugin-server"]
      interval: 60s
      timeout: 30s
      retries: 3

volumes:
  postgres-data:
  clickhouse-data:
  object_storage:
